// ADC opcodes
#define ADC_IM 0x69
#define ADC_ZP 0x65
#define ADC_ZPX 0x75
#define ADC_ABS 0x6D
#define ADC_ABSX 0x7D
#define ADC_ABSY 0x79
#define ADC_INDX 0x61
#define ADC_INDY 0x71
// AND opcodes
#define AND_IM 0x29
#define AND_ZP 0x25
#define AND_ZPX 0x35
#define AND_ABS 0x2D
#define AND_ABSX 0x3D
#define AND_ABSY 0x39
#define AND_INDX 0x21
#define AND_INDY 0x31
// ASL opcodes
#define ASL_AC 0x0A
#define ASL_ZP 0x06
#define ASL_ZPX 0x16
#define ASL_ABS 0x0E
#define ASL_ABSX 0x1E
// BCC opcodes
#define BCC 0x90
// BCS opcodes
#define BCS 0xB0
// BEQ opcodes
#define BEQ 0xF0
// BIT opcodes
#define BIT_ZP 0x24
#define BIT_ABS 0x2C
// BMI opcodes
#define BMI 0x30
// BNE opcodes
#define BNE 0xD0
// BPL opcodes
#define BPL 0x10
// BRK opcodes
#define BRK 0x00
// BVC opcodes
#define BVC 0x50
// BVS opcodes
#define BVS 0x70
// CLC opcodes
#define CLC 0x18
// CLD opcodes
#define CLD 0xD8
// CLI opcodes
#define CLI 0x58
// CLV opcodes
#define CLV 0xB8
// CMP opcodes
#define CMP_IM 0xC9
#define CMP_ZP 0xC5
#define CMP_ZPX 0xD5
#define CMP_ABS 0xCD
#define CMP_ABSX 0xDD
#define CMP_ABSY 0xD9
#define CMP_INDX 0xC1
#define CMP_INDY 0xD1
// LDA opcodes
#define LDA_IM 0xA9
#define LDA_ZP 0xA5
#define LDA_ZPX 0xB5
#define LDA_ABS 0xAD
#define LDA_ABSX 0xBD
#define LDA_ABSY 0xB9
#define LDA_INDX 0xA1
#define LDA_INDY 0xB1
// LDX opcodes
#define LDX_IM 0xA2
#define LDX_ZP 0xA6
#define LDX_ZPY 0xB6
#define LDX_ABS 0xAE
#define LDX_ABSY 0xBE
// LDY opcodes
#define LDY_IM 0xA0
#define LDY_ZP 0xA4
#define LDY_ZPX 0xB4
#define LDY_ABS 0xAC
#define LDY_ABSX 0xBC
// NOP
#define NOP 0xEA
// ORA opcodes
#define ORA_IM 0x09
#define ORA_ZP 0x05
#define ORA_ZPX 0x15
#define ORA_ABS 0x0D
#define ORA_ABSX 0x1D
#define ORA_ABSY 0x19
#define ORA_INDX 0x01
#define ORA_INDY 0x11
// PHA opcodes
#define PHA 0x48
// PHP opcodes
#define PHP 0x08
// PLA opcodes
#define PLA 0x68
// PLP opcodes
#define PLP 0x28
// ROL opcodes
#define ROL_AC 0x2A
#define ROL_ZP 0x26
#define ROL_ZPX 0x36
#define ROL_ABS 0x2E
#define ROL_ABSX 0x3E
// ROR opcodes
#define ROR_AC 0x6A
#define ROR_ZP 0x66
#define ROR_ZPX 0x76
#define ROR_ABS 0x6E
#define ROR_ABSX 0x7E
// Jump and return
#define JSR_ABS 0x20
#define RTS 0x60