// ADC opcodes
#define ADC_IM 0x69
#define ADC_ZP 0x65
#define ADC_ZPX 0x75
#define ADC_ABS 0x6D
#define ADC_ABSX 0x7D
#define ADC_ABSY 0x79
#define ADC_INDX 0x61
#define ADC_INDY 0x71
// LDA opcodes
#define LDA_IM 0xA9
#define LDA_ZP 0xA5
#define LDA_ZPX 0xB5
#define LDA_ABS 0xAD
#define LDA_ABSX 0xBD
#define LDA_ABSY 0xB9
#define LDA_INDX 0xA1
#define LDA_INDY 0xB1
// LDX opcodes
#define LDX_IM 0xA2
#define LDX_ZP 0xA6
#define LDX_ZPY 0xB6
#define LDX_ABS 0xAE
#define LDX_ABSY 0xBE
// LDY opcodes
#define LDY_IM 0xA0
#define LDY_ZP 0xA4
#define LDY_ZPX 0xB4
#define LDY_ABS 0xAC
#define LDY_ABSX 0xBC
// NOP
#define NOP 0xEA
// ORA opcodes
#define ORA_IM 0x09
#define ORA_ZP 0x05
#define ORA_ZPX 0x15
#define ORA_ABS 0x0D
#define ORA_ABSX 0x1D
#define ORA_ABSY 0x19
#define ORA_INDX 0x01
#define ORA_INDY 0x11
// PHA opcodes
#define PHA 0x48
// PHP opcodes
#define PHP 0x08
// PLA opcodes
#define PLA 0x68
// PLP opcodes
#define PLP 0x28
// ROL opcodes
#define ROL_AC 0x2A
#define ROL_ZP 0x26
#define ROL_ZPX 0x36
#define ROL_ABS 0x2E
#define ROL_ABSX 0x3E
// ROR opcodes
#define ROR_AC 0x6A
#define ROR_ZP 0x66
#define ROR_ZPX 0x76
#define ROR_ABS 0x6E
#define ROR_ABSX 0x7E
// Jump and return
#define JSR_ABS 0x20
#define RTS 0x60